package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.repositories.IOrderHistoryRepository;
import dao.uow.IUnitOfWork;
import domain.model.OrderHistory;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;

public class OrderHistoryRepository extends RepositoryBase<OrderHistory>
implements IOrderHistoryRepository {


    public OrderHistoryRepository(Connection connection,
                                  IMapResultSetIntoEntity<OrderHistory> mapper, IUnitOfWork uow) {
        super(connection, mapper, uow);

    }

    @Override
    protected String createTableSql() {
        return "" + "CREATE TABLE history("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,"
                + "date DATE,"
                + "amount DECIMAL,"
                + "BEER_ID int,"
                + "FOREIGN KEY (FROM_ID) REFERENCES beer(id),"
                + ")";
    }

    @Override
    protected String tableName() {
        return "OrderHistory";

    }

    @Override
    protected String insertSql() {
        return "INSERT INTO history("
                + "date, "
                + "amount, "
                + " BEER_ID"
                + ") VALUES (?,?,?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE HISTORY SET ("
                + "date, "
                + "amount, "
                + " BEER_ID"
                + ") VALUES (?,?,?)) WHERE id = ?";
    }

    @Override
    protected void setUpdate(OrderHistory orderHistory) throws SQLException {
        update.setDate(1, orderHistory.getDate());
        update.setDouble(2, orderHistory.getAmount());
        update.setInt(3, orderHistory.getBeerId().getId());
        update.setInt(4, orderHistory.getId());

    }

    @Override
    protected void setInsert(OrderHistory orderHistory) throws SQLException {
        update.setDate(1, orderHistory.getDate());
        update.setDouble(2, orderHistory.getAmount());
        update.setInt(3, orderHistory.getBeerId().getId());
        update.setInt(4, orderHistory.getId());
    }


        public List<OrderHistory> fromName (String beerName){
            // TODO Auto-generated method stub
            return null;
        }

     public List<OrderHistory> ofBrewery (String brewery){
        // TODO Auto-generated method stub
        return null;
    }


        public List<OrderHistory> withDate (Date ofPurchase){
            // TODO Auto-generated method stub
            return null;
        }
    }
